[package]
name = "ctime"
version = "0.1.0"
edition = "2021"
author = "SpacePengwin"
description = "Command line utility to get run-time from a Windows, MacOS, or Unix system program."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
